project:
  type: book

book:
  author: "Sébastien Lê"

profile:
  group:
    - [fr, en]
  default: fr

format:
  html:
    theme: flatly
    toc: true
    number-sections: true
    fig-cap-location: bottom

  pdf:
    documentclass: scrreprt
    toc: true

editor: visual
